# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(760, 597)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setEnabled(True)
        self.graphicsView.setGeometry(QtCore.QRect(10, 10, 550, 550))
        self.graphicsView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.graphicsView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.graphicsView.setRenderHints(QtGui.QPainter.NonCosmeticDefaultPen|QtGui.QPainter.SmoothPixmapTransform|QtGui.QPainter.TextAntialiasing)
        self.graphicsView.setTransformationAnchor(QtWidgets.QGraphicsView.NoAnchor)
        self.graphicsView.setObjectName("graphicsView")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(570, 10, 184, 535))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setMaximumSize(QtCore.QSize(10, 21))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.rotateXLineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.rotateXLineEdit.setMaximumSize(QtCore.QSize(51, 21))
        self.rotateXLineEdit.setObjectName("rotateXLineEdit")
        self.horizontalLayout.addWidget(self.rotateXLineEdit)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setMaximumSize(QtCore.QSize(10, 21))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.rotateYLineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.rotateYLineEdit.setMaximumSize(QtCore.QSize(51, 21))
        self.rotateYLineEdit.setObjectName("rotateYLineEdit")
        self.horizontalLayout.addWidget(self.rotateYLineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setMaximumSize(QtCore.QSize(30, 21))
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.rotateAngleLineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.rotateAngleLineEdit.setMaximumSize(QtCore.QSize(51, 21))
        self.rotateAngleLineEdit.setObjectName("rotateAngleLineEdit")
        self.horizontalLayout_2.addWidget(self.rotateAngleLineEdit)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.rotateButton = QtWidgets.QPushButton(self.layoutWidget)
        self.rotateButton.setObjectName("rotateButton")
        self.verticalLayout.addWidget(self.rotateButton)
        self.verticalLayout_4.addLayout(self.verticalLayout)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_6.addWidget(self.label_6)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        self.label_7.setMaximumSize(QtCore.QSize(10, 21))
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_3.addWidget(self.label_7)
        self.scaleXLineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.scaleXLineEdit.setMaximumSize(QtCore.QSize(51, 21))
        self.scaleXLineEdit.setObjectName("scaleXLineEdit")
        self.horizontalLayout_3.addWidget(self.scaleXLineEdit)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget)
        self.label_8.setMaximumSize(QtCore.QSize(10, 21))
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_3.addWidget(self.label_8)
        self.scaleYLineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.scaleYLineEdit.setMaximumSize(QtCore.QSize(51, 21))
        self.scaleYLineEdit.setObjectName("scaleYLineEdit")
        self.horizontalLayout_3.addWidget(self.scaleYLineEdit)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(0, -1, 5, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_9 = QtWidgets.QLabel(self.layoutWidget)
        self.label_9.setMaximumSize(QtCore.QSize(15, 21))
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_4.addWidget(self.label_9)
        self.scaleKxLineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.scaleKxLineEdit.setMaximumSize(QtCore.QSize(51, 21))
        self.scaleKxLineEdit.setObjectName("scaleKxLineEdit")
        self.horizontalLayout_4.addWidget(self.scaleKxLineEdit)
        self.label_10 = QtWidgets.QLabel(self.layoutWidget)
        self.label_10.setMaximumSize(QtCore.QSize(15, 21))
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_4.addWidget(self.label_10)
        self.scaleKyLineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.scaleKyLineEdit.setMaximumSize(QtCore.QSize(51, 21))
        self.scaleKyLineEdit.setObjectName("scaleKyLineEdit")
        self.horizontalLayout_4.addWidget(self.scaleKyLineEdit)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)
        self.scaleButton = QtWidgets.QPushButton(self.layoutWidget)
        self.scaleButton.setObjectName("scaleButton")
        self.verticalLayout_6.addWidget(self.scaleButton)
        self.verticalLayout_4.addLayout(self.verticalLayout_6)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_11 = QtWidgets.QLabel(self.layoutWidget)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_2.addWidget(self.label_11)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(0, -1, 5, -1)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_14 = QtWidgets.QLabel(self.layoutWidget)
        self.label_14.setMaximumSize(QtCore.QSize(15, 21))
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_6.addWidget(self.label_14)
        self.moveDxLineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.moveDxLineEdit.setMaximumSize(QtCore.QSize(51, 21))
        self.moveDxLineEdit.setObjectName("moveDxLineEdit")
        self.horizontalLayout_6.addWidget(self.moveDxLineEdit)
        self.label_15 = QtWidgets.QLabel(self.layoutWidget)
        self.label_15.setMaximumSize(QtCore.QSize(15, 21))
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_6.addWidget(self.label_15)
        self.moveDyLineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.moveDyLineEdit.setMaximumSize(QtCore.QSize(51, 21))
        self.moveDyLineEdit.setObjectName("moveDyLineEdit")
        self.horizontalLayout_6.addWidget(self.moveDyLineEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.moveButton = QtWidgets.QPushButton(self.layoutWidget)
        self.moveButton.setObjectName("moveButton")
        self.verticalLayout_2.addWidget(self.moveButton)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_12 = QtWidgets.QLabel(self.layoutWidget)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_3.addWidget(self.label_12)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.stepBackButton = QtWidgets.QPushButton(self.layoutWidget)
        self.stepBackButton.setObjectName("stepBackButton")
        self.horizontalLayout_5.addWidget(self.stepBackButton)
        self.stepForwardButton = QtWidgets.QPushButton(self.layoutWidget)
        self.stepForwardButton.setObjectName("stepForwardButton")
        self.horizontalLayout_5.addWidget(self.stepForwardButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.defaultImageButton = QtWidgets.QPushButton(self.layoutWidget)
        self.defaultImageButton.setMinimumSize(QtCore.QSize(0, 60))
        self.defaultImageButton.setMaximumSize(QtCore.QSize(16777215, 60))
        self.defaultImageButton.setObjectName("defaultImageButton")
        self.verticalLayout_3.addWidget(self.defaultImageButton)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Поворот"))
        self.label_2.setText(_translate("MainWindow", "X"))
        self.rotateXLineEdit.setText(_translate("MainWindow", "0"))
        self.label_3.setText(_translate("MainWindow", "Y"))
        self.rotateYLineEdit.setText(_translate("MainWindow", "0"))
        self.label_4.setText(_translate("MainWindow", "Угол"))
        self.rotateAngleLineEdit.setText(_translate("MainWindow", "0"))
        self.label_5.setText(_translate("MainWindow", "в градусах"))
        self.rotateButton.setText(_translate("MainWindow", "Выполнить"))
        self.label_6.setText(_translate("MainWindow", "Масштабирование"))
        self.label_7.setText(_translate("MainWindow", "X"))
        self.scaleXLineEdit.setText(_translate("MainWindow", "0"))
        self.label_8.setText(_translate("MainWindow", "Y"))
        self.scaleYLineEdit.setText(_translate("MainWindow", "0"))
        self.label_9.setText(_translate("MainWindow", "kx"))
        self.scaleKxLineEdit.setText(_translate("MainWindow", "0"))
        self.label_10.setText(_translate("MainWindow", "ky"))
        self.scaleKyLineEdit.setText(_translate("MainWindow", "0"))
        self.scaleButton.setText(_translate("MainWindow", "Выполнить"))
        self.label_11.setText(_translate("MainWindow", "Перемещение"))
        self.label_14.setText(_translate("MainWindow", "dx"))
        self.moveDxLineEdit.setText(_translate("MainWindow", "0"))
        self.label_15.setText(_translate("MainWindow", "dy"))
        self.moveDyLineEdit.setText(_translate("MainWindow", "0"))
        self.moveButton.setText(_translate("MainWindow", "Выполнить"))
        self.label_12.setText(_translate("MainWindow", "Шаг"))
        self.stepBackButton.setText(_translate("MainWindow", "назад"))
        self.stepForwardButton.setText(_translate("MainWindow", "вперед"))
        self.defaultImageButton.setText(_translate("MainWindow", "Вернуть исходное\n"
"изображение"))

