# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interfaceWindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(625, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 30, 621, 42))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(50, 110, 239, 456))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.label_11 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_2.addWidget(self.label_11)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEditStartX = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEditStartX.setObjectName("lineEditStartX")
        self.horizontalLayout.addWidget(self.lineEditStartX)
        self.lineEditEndX = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEditEndX.setObjectName("lineEditEndX")
        self.horizontalLayout.addWidget(self.lineEditEndX)
        self.lineEditStepX = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEditStepX.setObjectName("lineEditStepX")
        self.horizontalLayout.addWidget(self.lineEditStepX)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.checkBoxMulti = QtWidgets.QCheckBox(self.layoutWidget1)
        self.checkBoxMulti.setObjectName("checkBoxMulti")
        self.verticalLayout_2.addWidget(self.checkBoxMulti)
        self.label_12 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_2.addWidget(self.label_12)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_13 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_3.addWidget(self.label_13)
        self.label_14 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_3.addWidget(self.label_14)
        self.label_15 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_3.addWidget(self.label_15)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lineEditStartY = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEditStartY.setObjectName("lineEditStartY")
        self.horizontalLayout_4.addWidget(self.lineEditStartY)
        self.lineEditEndY = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEditEndY.setObjectName("lineEditEndY")
        self.horizontalLayout_4.addWidget(self.lineEditEndY)
        self.lineEditStepY = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEditStepY.setObjectName("lineEditStepY")
        self.horizontalLayout_4.addWidget(self.lineEditStepY)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.pushButtonChangeTable = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButtonChangeTable.setObjectName("pushButtonChangeTable")
        self.verticalLayout_2.addWidget(self.pushButtonChangeTable)
        self.pushButtonShowTable = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButtonShowTable.setObjectName("pushButtonShowTable")
        self.verticalLayout_2.addWidget(self.pushButtonShowTable)
        self.textEdit = QtWidgets.QTextEdit(self.layoutWidget1)
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_2.addWidget(self.textEdit)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(310, 220, 261, 121))
        self.widget.setObjectName("widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_18 = QtWidgets.QLabel(self.widget)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_7.addWidget(self.label_18)
        self.lineEditNX = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditNX.sizePolicy().hasHeightForWidth())
        self.lineEditNX.setSizePolicy(sizePolicy)
        self.lineEditNX.setObjectName("lineEditNX")
        self.horizontalLayout_7.addWidget(self.lineEditNX)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_19 = QtWidgets.QLabel(self.widget)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_8.addWidget(self.label_19)
        self.lineEditX = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditX.sizePolicy().hasHeightForWidth())
        self.lineEditX.setSizePolicy(sizePolicy)
        self.lineEditX.setObjectName("lineEditX")
        self.horizontalLayout_8.addWidget(self.lineEditX)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_16 = QtWidgets.QLabel(self.widget)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_5.addWidget(self.label_16)
        self.lineEditNY = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditNY.sizePolicy().hasHeightForWidth())
        self.lineEditNY.setSizePolicy(sizePolicy)
        self.lineEditNY.setObjectName("lineEditNY")
        self.horizontalLayout_5.addWidget(self.lineEditNY)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_17 = QtWidgets.QLabel(self.widget)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_6.addWidget(self.label_17)
        self.lineEditY = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditY.sizePolicy().hasHeightForWidth())
        self.lineEditY.setSizePolicy(sizePolicy)
        self.lineEditY.setObjectName("lineEditY")
        self.horizontalLayout_6.addWidget(self.lineEditY)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.widget1 = QtWidgets.QWidget(self.centralwidget)
        self.widget1.setGeometry(QtCore.QRect(310, 110, 261, 104))
        self.widget1.setObjectName("widget1")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_2 = QtWidgets.QLabel(self.widget1)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_5.addWidget(self.label_2)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.radioButtonNewton = QtWidgets.QRadioButton(self.widget1)
        self.radioButtonNewton.setAcceptDrops(True)
        self.radioButtonNewton.setChecked(True)
        self.radioButtonNewton.setObjectName("radioButtonNewton")
        self.verticalLayout_4.addWidget(self.radioButtonNewton)
        self.radioButtonSpline = QtWidgets.QRadioButton(self.widget1)
        self.radioButtonSpline.setChecked(False)
        self.radioButtonSpline.setObjectName("radioButtonSpline")
        self.verticalLayout_4.addWidget(self.radioButtonSpline)
        self.radioButtonMulti = QtWidgets.QRadioButton(self.widget1)
        self.radioButtonMulti.setObjectName("radioButtonMulti")
        self.verticalLayout_4.addWidget(self.radioButtonMulti)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.widget2 = QtWidgets.QWidget(self.centralwidget)
        self.widget2.setGeometry(QtCore.QRect(310, 350, 261, 80))
        self.widget2.setObjectName("widget2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget2)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.pushButtonFindResult = QtWidgets.QPushButton(self.widget2)
        self.pushButtonFindResult.setObjectName("pushButtonFindResult")
        self.verticalLayout_6.addWidget(self.pushButtonFindResult)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.formLayout_2.setObjectName("formLayout_2")
        self.textEditResult = QtWidgets.QTextEdit(self.widget2)
        self.textEditResult.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEditResult.sizePolicy().hasHeightForWidth())
        self.textEditResult.setSizePolicy(sizePolicy)
        self.textEditResult.setMaximumSize(QtCore.QSize(125, 20))
        self.textEditResult.setReadOnly(True)
        self.textEditResult.setObjectName("textEditResult")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.textEditResult)
        self.label_10 = QtWidgets.QLabel(self.widget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setMaximumSize(QtCore.QSize(400, 25))
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.label_7 = QtWidgets.QLabel(self.widget2)
        self.label_7.setObjectName("label_7")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.textEditRightResult = QtWidgets.QTextEdit(self.widget2)
        self.textEditRightResult.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEditRightResult.sizePolicy().hasHeightForWidth())
        self.textEditRightResult.setSizePolicy(sizePolicy)
        self.textEditRightResult.setMaximumSize(QtCore.QSize(125, 20))
        self.textEditRightResult.setReadOnly(True)
        self.textEditRightResult.setObjectName("textEditRightResult")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.textEditRightResult)
        self.verticalLayout_6.addLayout(self.formLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Аппроксимация функций"))
        self.label_3.setText(_translate("MainWindow", "Работа с таблицей"))
        self.label_11.setText(_translate("MainWindow", "X"))
        self.label_4.setText(_translate("MainWindow", "От"))
        self.label_5.setText(_translate("MainWindow", "До"))
        self.label_6.setText(_translate("MainWindow", "Шаг"))
        self.checkBoxMulti.setText(_translate("MainWindow", "для многомерной"))
        self.label_12.setText(_translate("MainWindow", "Y"))
        self.label_13.setText(_translate("MainWindow", "От"))
        self.label_14.setText(_translate("MainWindow", "До"))
        self.label_15.setText(_translate("MainWindow", "Шаг"))
        self.pushButtonChangeTable.setText(_translate("MainWindow", "Изменить текущую \n"
"таблицу"))
        self.pushButtonShowTable.setText(_translate("MainWindow", "Показать текущую \n"
"таблицу"))
        self.label_18.setText(_translate("MainWindow", "Введите nx >= 0"))
        self.label_19.setText(_translate("MainWindow", "Введите x:"))
        self.label_16.setText(_translate("MainWindow", "Введите ny >= 0"))
        self.label_17.setText(_translate("MainWindow", "Введите y:"))
        self.label_2.setText(_translate("MainWindow", "Поиск значения"))
        self.radioButtonNewton.setText(_translate("MainWindow", "Полином Ньютона"))
        self.radioButtonSpline.setText(_translate("MainWindow", "Сплайн"))
        self.radioButtonMulti.setText(_translate("MainWindow", "Многомерная"))
        self.pushButtonFindResult.setText(_translate("MainWindow", "Найти значения"))
        self.label_10.setText(_translate("MainWindow", "Результат:          "))
        self.label_7.setText(_translate("MainWindow", "Точный результат"))

